// Generated by CoffeeScript 2.3.2
var form, menu, nullfunc, rmfunc, search;

form = null;

menu = null;

search = function() {
  var a, entry, i, len, li, result, results;
  if (menu) {
    menu.remove();
  }
  if (form.val().length === 0) {
    return;
  }
  result = searchFAQ(form.val());
  menu = $('<div>').css('background-color', '#dff').css('max-height', '160px').css('overflow', 'scroll').css('float', 'left');
  $('.searchKeyword').append(menu);
  results = [];
  for (i = 0, len = result.length; i < len; i++) {
    entry = result[i];
    a = $('<a>');
    a.attr('href', entry['faq']['url']);
    a.text(entry['faq']['title']);
    li = $('<li>').css('font-size', '12px');
    li.append(a);
    results.push(menu.append(li));
  }
  return results;
};

nullfunc = function() {};

rmfunc = function() {
  $('#keyword').removeClass('SearchAssist');
  return $(".sug_list").remove();
};

$(function() {
  var style;
  form = $("#keyword");
  form.on('keyup', search);
  form.on('mousedown', search);
  setInterval(rmfunc, 200);
  style = $('<style>');
  style.text("a:visited, a:link { color: #22f; }");
  return $('head').append(style);
});
